ci:
  autoupdate_commit_msg: 'chore: [pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
              .*\.csv
          )$
      - id: mixed-line-ending
        exclude: >
          (?x)^(
              .*\.csv|
              .*\.css
          )$
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: >
          (?x)^(
              .*\.csv
          )$

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.4
    hooks:
      - id: check-github-workflows
        args: ['--verbose']

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 'v3.9.4'
    hooks:
      - id: prettier
        types_or: [yaml, html, css, scss, javascript, json, toml]
        args: [--prose-wrap=always, --single-quote]

  - repo: https://github.com/FlamingTempura/bibtex-tidy
    rev: v1.14.0
    hooks:
      - id: bibtex-tidy
        files: \.bib$
        args:
          - '--curly'
          - '--numeric'
          - '--tab'
          - '--align=13'
          - '--duplicates=key,doi'
          - '--no-escape'
          - '--sort-fields=title,shorttitle,author,year,month,day,journal,booktitle,location,on,publisher,address,series,volume,number,pages,doi,isbn,issn,url,urldate,copyright,category,note,metadata'
          - '--no-remove-dupe-fields'
