# Copyright 2025 Pasteur Labs. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Tesseract API module for {{name}}
# Generated by tesseract {{version}} on {{timestamp}}

from typing import Any, Callable

import equinox as eqx
import jax
import jax.numpy as jnp
from pydantic import BaseModel, Field

from tesseract_core.runtime import Differentiable, Float32, Array, ShapeDType
from tesseract_core.runtime.tree_transforms import filter_func, flatten_with_paths


# Import JAX-FEM specific modules.
from jax_fem.problem import Problem
from jax_fem.solver import solver, ad_wrapper
from jax_fem.generate_mesh import get_meshio_cell_type, Mesh, rectangle_mesh

#
# Schemata
#

class InputSchema(BaseModel):
    rho: Differentiable[
        Array[
            (
                None,
                None,
            ),
            "float32",
        ]
    ] = Field(description="2D density field for topology optimization")

    Lx: float = Field(
        default=60.0,
        description="Length of the simulation box in the x direction."
    )
    Ly: float = Field(
        default=30.0,
        description="Length of the plane in the y direction. This is a scalar value that defines the size of the plane along the y-axis."
    )   
    Nx: int = Field(
        default=60,
        description="Number of elements in the x direction. This is an integer value that defines the resolution of the mesh along the x-axis."
    )
    Ny: int = Field(
        default=30,
        description="Number of elements in the y direction. This is an integer value that defines the resolution of the mesh along the y-axis."
    )


class OutputSchema(BaseModel):
    compliance: Differentiable[
        Array[
            (),
            "float32",
        ]
    ] = Field(
        description="Compliance of the structure, a measure of stiffness"
    )
 

#
# Required endpoints
#


# Define constitutive relationship. 
# Generally, JAX-FEM solves -div.(f(u_grad,alpha_1,alpha_2,...,alpha_N)) = b. 
# Here, we have f(u_grad,alpha_1,alpha_2,...,alpha_N) = sigma(u_grad, theta),
# reflected by the function 'stress'. The functions 'custom_init'and 'set_params' 
# override base class methods. In particular, set_params sets the design variable theta.
class Elasticity(Problem):
    def custom_init(self):
        # Override base class method.
        # Set up 'self.fe.flex_inds' so that location-specific TO can be realized.
        self.fe = self.fes[0]
        self.fe.flex_inds = jnp.arange(len(self.fe.cells))

    def get_tensor_map(self):
        def stress(u_grad, theta):
            # Plane stress assumption
            # Reference: https://en.wikipedia.org/wiki/Hooke%27s_law
            Emax = 70.e3
            Emin = 1e-3*Emax
            nu = 0.3
            penal = 3.
            E = Emin + (Emax - Emin)*theta[0]**penal
            epsilon = 0.5*(u_grad + u_grad.T)
            eps11 = epsilon[0, 0]
            eps22 = epsilon[1, 1]
            eps12 = epsilon[0, 1]
            sig11 = E/(1 + nu)/(1 - nu)*(eps11 + nu*eps22) 
            sig22 = E/(1 + nu)/(1 - nu)*(nu*eps11 + eps22)
            sig12 = E/(1 + nu)*eps12
            sigma = jnp.array([[sig11, sig12], [sig12, sig22]])
            return sigma
        return stress

    def get_surface_maps(self):
        def surface_map(u, x):
            return jnp.array([0., 100.])
        return [surface_map]

    def set_params(self, params):
        # Override base class method.
        full_params = jnp.ones((self.fe.num_cells, params.shape[1]))
        full_params = full_params.at[self.fe.flex_inds].set(params)
        thetas = jnp.repeat(full_params[:, None, :], self.fe.num_quads, axis=1)
        self.full_params = full_params
        self.internal_vars = [thetas]

    def compute_compliance(self, sol):
        # Surface integral
        boundary_inds = self.boundary_inds_list[0]
        _, nanson_scale = self.fe.get_face_shape_grads(boundary_inds)
        # (num_selected_faces, 1, num_nodes, vec) * # (num_selected_faces, num_face_quads, num_nodes, 1)    
        u_face = sol[self.fe.cells][boundary_inds[:, 0]][:, None, :, :] * self.fe.face_shape_vals[boundary_inds[:, 1]][:, :, :, None]
        u_face = jnp.sum(u_face, axis=2) # (num_selected_faces, num_face_quads, vec)
        # (num_selected_faces, num_face_quads, dim)
        subset_quad_points = self.physical_surface_quad_points[0]
        neumann_fn = self.get_surface_maps()[0]
        traction = -jax.vmap(jax.vmap(neumann_fn))(u_face, subset_quad_points) # (num_selected_faces, num_face_quads, vec)
        val = jnp.sum(traction * u_face * nanson_scale[:, :, None])
        return val


def setup(
    Nx: int = 60,
    Ny: int = 30,
    Lx: float = 60.0,
    Ly: float = 30.0,
) -> tuple[Elasticity, Callable]:
        
    # Specify mesh-related information. We use first-order quadrilateral element.
    ele_type = 'QUAD4'
    cell_type = get_meshio_cell_type(ele_type)
    meshio_mesh = rectangle_mesh(Nx=Nx, Ny=Ny, domain_x=Lx, domain_y=Ly)
    mesh = Mesh(meshio_mesh.points, meshio_mesh.cells_dict[cell_type])

    # Define boundary conditions and values.
    def fixed_location(point):
        return jnp.isclose(point[0], 0., atol=1e-5)
        
    def load_location(point):
        return jnp.logical_and(jnp.isclose(point[0], Lx, atol=1e-5), jnp.isclose(point[1], 0., atol=0.1*Ly + 1e-5))

    def dirichlet_val(point):
        return 0.

    dirichlet_bc_info = [[fixed_location]*2, [0, 1], [dirichlet_val]*2]

    location_fns = [load_location]

    # Define forward problem.
    return Elasticity(mesh, vec=2, dim=2, ele_type=ele_type, dirichlet_bc_info=dirichlet_bc_info, location_fns=location_fns)

problem_cache = None
fwd_pred_cache = None

def apply_jit(inputs: dict) -> dict:

    with jax.ensure_compile_time_eval():
        global problem_cache
        global fwd_pred_cache

        if problem_cache is None or fwd_pred_cache is None:
            # Initialize the problem and forward prediction function.
            problem = setup(
                Nx=inputs["Nx"],
                Ny=inputs["Ny"],
                Lx=inputs["Lx"],
                Ly=inputs["Ly"],
            )
            problem_cache = problem

            # Apply the automatic differentiation wrapper. 
            # This is a critical step that makes the problem solver differentiable.
            fwd_pred = ad_wrapper(problem, solver_options={'umfpack_solver': {}}, adjoint_solver_options={'umfpack_solver': {}})

            fwd_pred_cache = fwd_pred

        else:
            # Use cached problem and forward prediction function.
            problem = problem_cache
            fwd_pred = fwd_pred_cache

    def J_total(rho):
        """
        Compute the compliance of the structure given a signed distance function (SDF).
        """
        # J(u(theta), theta)   
        sol_list = fwd_pred(rho)
        compliance = problem.compute_compliance(sol_list[0])
        return compliance

    return {
        "compliance": J_total(inputs["rho"])
    }


def apply(inputs: InputSchema) -> OutputSchema:

    out = apply_jit(inputs.model_dump())

    return out


#
# Jax-handled AD endpoints (no need to modify)
#


def vector_jacobian_product(
    inputs: InputSchema,
    vjp_inputs: set[str],
    vjp_outputs: set[str],
    cotangent_vector: dict[str, Any],
):

    assert vjp_inputs == {"rho"}
    assert vjp_outputs == {"compliance"}

    inputs = inputs.model_dump()

    filtered_apply = filter_func(apply_jit, inputs, vjp_outputs)
    _, vjp_func = jax.vjp(
        filtered_apply, flatten_with_paths(inputs, include_paths=vjp_inputs)
    )

    # convert to float 64
    cotangent_vector["compliance"] = jnp.asarray(cotangent_vector["compliance"], dtype=jnp.float64)

    return vjp_func(cotangent_vector)[0]


def abstract_eval(abstract_inputs):
    """Calculate output shape of apply from the shape of its inputs."""

    return {
        "compliance": ShapeDType(
            shape=(),
            dtype="float32"
        )
    }

