## Causal Bayesian NetworkX 

Humans are existence proofs for the solubility of computational causal inference.

Computational problems are sometimes thought to be the exclusive domain of computer science, though the solutions found prove vital for many other sciences. But computational cognitive science can also contribute to the solution of computational problems, particularly inductive problems. Causal inference (and inductive problems more generally) have proven resilient to traditional analysis, and the recent progress on these problems observed in machine learning (e.g., neural networks and their extensions) originate in models formulated by cognitive scientists.

As a computational cognitive scientist, I use a technique called rational analysis, which roughly consists of developing formal models of how *any* cognitive agent might optimally solve a computational problem and comparing that to how people actually solve analogous problems. In the course of doing so we find that people turn out to make much more sense than popular psychology might lead you to believe. At the same time, we create formal frameworks that represent entities and relations in the world as well as reasoning processes over those representations. 

One of the frameworks successfully used in this way are causal Bayesian networks. Bayesian networks fall within the more general class of probabilistic graphical models, specifically, directed acyclic graphs with associated conditional probability distributions. Directed arrows encode direct dependency relationships going from parents to their children, whose conditional probability distribution is defined in terms of the parents' values. *Causal* Bayesian networks are endowed with an intervention operation that allows "graph surgery" in which one cuts variables off from their parents (usually setting it to a particular value). 

In this talk, I will provide an introduction to causal Bayesian Networks, emphasizing network structure manipulation and sampling from conditional probability distributions, illustrated with [some tools I've developed on top of NetworkX](https://github.com/michaelpacer/Causal-Bayesian-NetworkX/blob/master/Basic%20Pieces%20of%20Causal%20Bayesian%20NetworkX.ipynb). 

<hr/>
### About the speaker
Mike has extensive speaking experience, having presented talks and posters and published associated papers at CogSci(2011, [2012](https://www.michaelpacer.com/s/elementsofCTcause.pdf)), NIPS ([2011](https://www.michaelpacer.com/s/PGNIPS2011continuous.pdf)) and UAI ([2013](https://www.michaelpacer.com/s/FormalExplanationModelUAI2013.pdf)). Other papers can be found at http://www.michaelpacer.com/peer-reviewed/.
