---
project:
  type: website

format:
  html:
    theme: darkly
  revealjs:
    footer: "{{< meta title >}}: <https://paddyroddy.github.io/talks>"
    hash-type: number
    history: false
    incremental: true
    link-external-icon: true
    link-external-newwindow: true
    mermaid:
      theme: dark
    slide-number: true
    theme: dark
    transition: fade

website:
  navbar:
    tools:
      - icon: house
        href: https://paddyroddy.github.io
        target: _blank
      - icon: github
        href: https://github.com/paddyroddy/talks
        target: _blank
  title: ""
